org.gradle.jvmargs = -Xmx3G
org.gradle.caching = true
# TODO - Fix
org.gradle.configuration-cache = false

# Mod Info
archives_base_name = CreateNumismatics
mod_version = 1.0.18
maven_group = dev.ithundxr.createnumismatics

minecraft_version = 1.21.1
enabled_platforms = neoforge

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version = 2024.11.17

# Fabric
# https://fabricmc.net/develop/
fabric_loader_version = 0.16.14
fabric_api_version = 0.116.4+1.21.1

# NeoForge
# https://neoforged.net/
neoforge_version = 21.1.187

# Create - Fabric
# https://modrinth.com/mod/create-fabric/versions
create_fabric_version = 6.0.0.0+mc1.20.1-build.1644
create_fabric_version_range = ~6.0.0

# Create - NeoForge
# https://wiki.createmod.net/developers/
create_neoforge_version = 6.0.6-104
ponder_version = 1.0.56
registrate_neoforge_version = MC1.21-1.3.0+62
flywheel_version = 1.0.4

# Development QOL
# EMI - https://modrinth.com/mod/emi/versions
emi_version = 1.1.22+1.21.1

# Mod Menu - https://modrinth.com/mod/modmenu/versions
modmenu_version = 11.0.3

# Carry On - https://github.com/Tschipp/CarryOn
carryon_neoforge_version = 2.2.3.3
carryon_fabric_version = 2.2.3.3
enable_carryon = false

# Publishing
# Modrinth
modrinth_id = Jdbbtt0i
# Curseforge
curseforge_id = 889722
