name: Bug Report
description: Create a bug report to help us improve Numismatics
labels: [ "type: bug" ]
body:
  -   type: textarea
      attributes:
        label: Describe the Bug
        description: A clear and concise description of what the bug is
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Reproduction Steps
        description: Tell us about the steps to reproduce the bug.
        value: |
          1.
          2.
          3.
          ...
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Expected Result
        description: A clear and concise description of what you expected to happen
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Screenshots and Videos
        description: If applicable, add screenshots or videos to help explain your problem.
      validations:
        required: false
  -   type: input
      attributes:
        label: Crash Report or Log
        description: If applicable, please add a **link** to the crash report or log that was created when this issue occurred. You can upload the crash report to a site like [mclogs](https://mclo.gs) or [Pastebin](https://pastebin.com). Please **do not** paste the whole crash report in this issue.
      validations:
        required: false
  -   type: input
      attributes:
        label: Operating System
        description: The operating system you were using when the bug occurred
        placeholder: Windows 11
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Mod Version
        description: The version of the mod you were using when the bug occurred
        options:
          - "1.0.6"
          - "1.0.5"
          - "1.0.4"
          - "1.0.2"
          - "1.0.1"
          - "1.0.0"
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Create Mod Version
        description: The version of **Create Mod** you were using when the bug occurred
        options:
          - "0.5.1f"
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the bug occurred
        options:
          - "1.20.1"
      validations:
        required: true
  -   type: input
      attributes:
        label: ModLoader and Version
        description: The **modloader** and **version** of the modloader using when the bug occurred
        placeholder: Fabric/Forge x.x.x
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Other Mods
        description: Please list any other mods that were running when the crash happened.
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Additional Context
        description: Add any extra context about the bug here
      validations:
        required: false
  -   type: markdown
      attributes:
        value: "Thank you for taking the time to make this bug report and helping improve Numismatics!"