blank_issues_enabled: true
contact_links:
  - name: I have a question!
    url: https://discord.gg/create-steam-n-rails-706277846389227612
    about: Join us on Discord and ask the community.
  - name: I have a suggestion or idea!
    url: https://discord.gg/create-steam-n-rails-706277846389227612
    about: These are best discussed with the community and submitted on Discord.
  - name: Talk to us on Discord.
    url: https://discord.gg/create-steam-n-rails-706277846389227612
    about: Ask questions and get help from the community.
